In [41]:
import pandas as pd
import numpy as np

In [42]:
seed = 42

root_path = "/home/stefan/kits-locala/muzee"

# Data

In [43]:
muzee = pd.read_csv(f"{root_path}/muzee.csv")

muzee.head()

,_id,codul entității muzeale,identificatorul înregistrării,județul,denumirea (română),denumirea cu localitate (română),denumirea (engleză),denumirea cu localitate (engleză),localitatea,unitatea administrativă,...,codul LMI al clădirii,codul SIRUTA al localității,data ultimei modificări,profilul principal (engleză),ordinul de acreditare,categoria (română),categoria (engleză),latitudine,longitudine,coordonatele
0,1,7083504,8,București,"Muzeul Memorial ""Dr. Victor Babeș""","Muzeul Memorial ""Dr. Victor Babeș"" - BUCUREȘTI",Dr. Victor Babeș Memorial Museum,Dr. Victor Babeș Memorial Museum - BUCHAREST,BUCUREȘTI,NaN,...,B-II-m-B-19267,179141.0,30.09.2013 12:50:47,Memorials -,NaN,Muzeu municipal,City museum,"44,460065","26,091329",muzeu
1,2,7300205,9,București,"Muzeul de Artă Veche Apuseană ""ing. Dumitru Mi...","Muzeul de Artă Veche Apuseană ""ing. Dumitru Mi...",Eng. Dumitru Minovici Western Old Art Museum,Eng. Dumitru Minovici Western Old Art Museum -...,BUCUREȘTI,NaN,...,B-II-m-A-19206,179141.0,05.12.2013 11:37:34,NaN,NaN,Muzeu în subordinea Academiei Române,Museum under the Romanian Academy,"44,484256","26,074651",muzeu
2,3,7084103,10,București,"Colecția de Artă Plastică ""Fr. Storck și Cecil...","Colecția de Artă Plastică ""Fr. și Cecilia Cuțe...",Fr. Storck and Cecilia Cuțescu Storck Fine Art...,Fr. Storck and Cecilia Cuțescu Storck Fine Art...,BUCUREȘTI,NaN,...,B-II-m-B-18332,179141.0,05.12.2013 11:37:34,NaN,NaN,Muzeu municipal,City museum,"44,450912","26,094471",muzeu
3,4,7300407,12,București,"Casa Memorială ""George și Agatha Bacovia""","Casa Memorială ""George și Agatha Bacovia"" - BU...",George and Agatha Bacovia Memorial House,George and Agatha Bacovia Memorial House - BUC...,BUCUREȘTI,NaN,...,NaN,179178.0,03.10.2013 16:08:28,NaN,NaN,Muzeu municipal,City museum,"44,397006","26,101241",muzeu
4,5,7300402,13,București,"Muzeul Memorial ""George Călinescu""","Muzeul Memorial ""George Călinescu"" - BUCUREȘTI",George Călinescu Memorial Museum,George Călinescu Memorial Museum - BUCHAREST,BUCUREȘTI,NaN,...,B-II-m-B-18411,179141.0,30.09.2013 12:50:47,NaN,NaN,Muzeu în subordinea Academiei Române,Museum under the Romanian Academy,"44,462162","26,099546",muzeu

# Subtask 1

In [44]:
subtask1 = len(muzee["denumirea (română)"])

subtask1

1008

# Subtask 2

In [45]:
subtask2 = len(muzee[muzee["județul"] == "București"])

subtask2

59

# Subtask 3

In [46]:
len(muzee.columns)

44

In [47]:
subtask3 = (muzee.isna().sum() > 0).sum()

subtask3

np.int64(33)

# Subtask 4

In [48]:
from copy import deepcopy

df = deepcopy(muzee)

df["an_fixed"] = df["anul înființării"].apply(
    lambda x: x.split(",")[0].split(";")[0] if type(x) == str else x
)

In [49]:
df.groupby("an_fixed")["codul entității muzeale"].nunique().sort_values(ascending=False)

an_fixed
2006           33
1971           22
2007           22
1957           20
1970           19
               ..
1895/1951       1
1904            1
1906            1
1958 (1973)     1
1953 -1955      1
Name: codul entității muzeale, Length: 132, dtype: int64

In [50]:
subtask4 = 2006

# Subtask 5

In [51]:
subtask5 = (
    muzee.groupby("județul")["codul entității muzeale"]
    .nunique()
    .sort_values(ascending=False)
)

subtask5

județul
Alba               60
București          59
Sibiu              47
Neamț              43
Prahova            41
Harghita           41
Dâmbovița          40
Suceava            40
Maramureș          37
Bacău              33
Iași               33
Timiș              31
Argeș              30
Vrancea            29
Constanța          29
Brașov             29
Cluj               27
Bihor              25
Gorj               25
Satu Mare          23
Vâlcea             23
Caraș-Severin      21
Olt                19
Bistrița-Năsăud    19
Arad               17
Galați             17
Tulcea             17
Hunedoara          17
Dolj               15
Covasna            14
Mureș              13
Botoșani           12
Vaslui             11
Brăila             10
Teleorman          10
Buzău               9
Mehedinți           9
Giurgiu             8
Ilfov               7
Ialomița            7
Călărași            7
Sălaj               4
Name: codul entității muzeale, dtype: int64

# Subtask 6

In [52]:
muzee.shape, len(muzee.columns), muzee.columns.size

((1008, 44), 44, 44)

In [53]:
subtask6 = round((muzee.notna().sum(axis=1)) / muzee.shape[1] * 100, 2)
subtask6

0       81.82
1       81.82
2       77.27
3       79.55
4       65.91
        ...
1003    72.73
1004    86.36
1005    72.73
1006    61.36
1007    79.55
Length: 1008, dtype: float64

In [54]:
muzee.shape

(1008, 44)

# Subtask 7

In [55]:
subtask7 = subtask6.mean()

subtask7

np.float64(72.58521825396825)

# Subtask 8

In [56]:
subtask8 = (subtask6 == subtask6.max()).sum() / len(muzee) * 100

subtask8 = float(subtask8.item())
subtask8

1.488095238095238

# Submission

In [57]:
def build_subtask(id, sid, ans):
    return pd.DataFrame({"id": id, "subtaskID": sid, "answer": ans})

subtasks = [
    ([1], 1, subtask1),
    ([2], 2, subtask2),
    ([3], 3, subtask3),
    ([4], 4, subtask4),
    (subtask5.index, 5, subtask5.values),
    (muzee["_id"], 6, subtask6),
    ([7], 7, subtask7),
    ([8], 8, subtask8),
]

submission = pd.concat([build_subtask(id, sid, ans) for id, sid, ans in subtasks])

In [58]:
submission.head()

     id  subtaskID  answer
0     1          1  1008.0
0     2          2    59.0
0     3          3    33.0
0     4          4  2006.0
0  Alba          5    60.0

In [59]:
submission.to_csv(f"{root_path}/submission.csv", index=False)