In [283]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import RidgeClassifier
from catboost import CatBoostClassifier

In [284]:
root_path = "/home/stefan/ioai-prep/kits/imprumuturi"
seed = 42

# Data

In [285]:
def prep_df(df: pd.DataFrame):
    df = df.drop(["customer_id", "loan_status"], axis=1, errors="ignore")

    cat_cols = df.select_dtypes(include='object')
    for col in cat_cols:
        dummies = pd.get_dummies(df[col], prefix=col, drop_first=True)
        df = pd.concat([df, dummies], axis=1)
        df = df.drop([col], axis=1)

    return df

In [286]:
df = pd.read_csv(f"{root_path}/train.csv")
df_train = prep_df(df)

In [287]:
df_train.head()

,age,years_employed,annual_income,credit_score,credit_history_years,savings_assets,current_debt,defaults_on_file,delinquencies_last_2yrs,derogatory_marks,...,payment_to_income_ratio,occupation_status_Self-Employed,occupation_status_Student,product_type_Line of Credit,product_type_Personal Loan,loan_intent_Debt Consolidation,loan_intent_Education,loan_intent_Home Improvement,loan_intent_Medical,loan_intent_Personal
0,40,14.1,77335,679,4.4,67,17026,0,0,0,...,0.113,True,False,False,True,False,True,False,False,False
1,18,0.0,34946,639,1.2,292,2620,0,1,0,...,0.357,False,False,False,True,False,True,False,False,False
2,29,9.4,26778,595,5.5,191,4702,1,1,0,...,0.651,False,False,False,True,False,False,False,False,True
3,27,1.5,25624,590,5.7,414,2609,0,0,0,...,0.062,False,True,False,True,True,False,False,False,False
4,18,0.0,25676,568,1.8,19,3453,1,1,1,...,0.321,False,False,False,True,False,False,False,True,False

# Models

In [289]:
X_train, X_test, y_train, y_test = train_test_split(df_train, df["loan_status"], test_size=0.2, random_state=seed)

In [290]:
def evaluate(model):
    cv = cross_val_score(model, X_train, y_train, scoring='roc_auc', cv=3, n_jobs=-1)
    cv = cv.mean() - cv.std()
    return cv.item()

In [291]:
ridge = RidgeClassifier(alpha=1)

evaluate(ridge)

0.941421928633207

In [ ]:
cb = CatBoostClassifier(random_state=seed)

evaluate(cb)

0:	total: 64.9ms	remaining: 2m 9s
0:	total: 65.9ms	remaining: 2m 11s
1:	total: 80.5ms	remaining: 1m 20s
1:	total: 84.1ms	remaining: 1m 24s
0:	total: 71.2ms	remaining: 2m 22s
2:	total: 102ms	remaining: 1m 7s
2:	total: 103ms	remaining: 1m 8s
3:	total: 115ms	remaining: 57.5s
3:	total: 119ms	remaining: 59.4s
1:	total: 95.6ms	remaining: 1m 35s
4:	total: 129ms	remaining: 51.5s
4:	total: 134ms	remaining: 53.6s
2:	total: 111ms	remaining: 1m 13s
5:	total: 150ms	remaining: 49.9s
5:	total: 150ms	remaining: 49.9s
3:	total: 126ms	remaining: 1m 3s
6:	total: 157ms	remaining: 44.7s
7:	total: 163ms	remaining: 40.5s
8:	total: 168ms	remaining: 37.3s
6:	total: 170ms	remaining: 48.3s
9:	total: 174ms	remaining: 34.6s
4:	total: 150ms	remaining: 60s
7:	total: 190ms	remaining: 47.4s
5:	total: 166ms	remaining: 55.2s
10:	total: 195ms	remaining: 35.2s
11:	total: 205ms	remaining: 34s
6:	total: 184ms	remaining: 52.3s
8:	total: 211ms	remaining: 46.7s
12:	total: 211ms	remaining: 32.2s
13:	total: 221ms	remaining: 31.3s
7:	total: 205ms	remaining: 51s
9:	total: 232ms	remaining: 46.1s
14:	total: 231ms	remaining: 30.5s
15:	total: 239ms	remaining: 29.6s
8:	total: 218ms	remaining: 48.2s
16:	total: 245ms	remaining: 28.6s
10:	total: 249ms	remaining: 45.1s
17:	total: 251ms	remaining: 27.6s
9:	total: 234ms	remaining: 46.5s
18:	total: 257ms	remaining: 26.8s
19:	total: 264ms	remaining: 26.1s
11:	total: 268ms	remaining: 44.4s
20:	total: 274ms	remaining: 25.8s
10:	total: 254ms	remaining: 45.9s
12:	total: 283ms	remaining: 43.2s
21:	total: 293ms	remaining: 26.3s
11:	total: 271ms	remaining: 44.8s
13:	total: 295ms	remaining: 41.8s
22:	total: 305ms	remaining: 26.2s
23:	total: 310ms	remaining: 25.5s
14:	total: 318ms	remaining: 42.1s
24:	total: 316ms	remaining: 25s
12:	total: 298ms	remaining: 45.6s
25:	total: 323ms	remaining: 24.5s
26:	total: 328ms	remaining: 24s
15:	total: 336ms	remaining: 41.7s
27:	total: 335ms	remaining: 23.6s
28:	total: 340ms	remaining: 23.1s
13:	total: 324ms	remaining: 46s
29:	total: 346ms	remaining: 22.7s
16:	total: 355ms	remaining: 41.4s
30:	total: 353ms	remaining: 22.4s
31:	total: 359ms	remaining: 22.1s
14:	total: 343ms	remaining: 45.4s
17:	total: 372ms	remaining: 41s
32:	total: 367ms	remaining: 21.9s
33:	total: 374ms	remaining: 21.6s
34:	total: 381ms	remaining: 21.4s
18:	total: 392ms	remaining: 40.9s
15:	total: 369ms	remaining: 45.7s
35:	total: 390ms	remaining: 21.3s
19:	total: 407ms	remaining: 40.3s
36:	total: 406ms	remaining: 21.6s
16:	total: 395ms	remaining: 46.1s
20:	total: 421ms	remaining: 39.7s
37:	total: 422ms	remaining: 21.8s
21:	total: 435ms	remaining: 39.1s
17:	total: 414ms	remaining: 45.5s
38:	total: 439ms	remaining: 22.1s
22:	total: 451ms	remaining: 38.8s
18:	total: 433ms	remaining: 45.2s
39:	total: 458ms	remaining: 22.4s
23:	total: 465ms	remaining: 38.2s
19:	total: 452ms	remaining: 44.7s
40:	total: 476ms	remaining: 22.7s
24:	total: 487ms	remaining: 38.5s
41:	total: 484ms	remaining: 22.6s
42:	total: 494ms	remaining: 22.5s
25:	total: 502ms	remaining: 38.1s
20:	total: 483ms	remaining: 45.5s
26:	total: 516ms	remaining: 37.7s
43:	total: 512ms	remaining: 22.7s
21:	total: 503ms	remaining: 45.2s
27:	total: 529ms	remaining: 37.3s
44:	total: 525ms	remaining: 22.8s
28:	total: 541ms	remaining: 36.8s
45:	total: 543ms	remaining: 23.1s
29:	total: 551ms	remaining: 36.2s
22:	total: 528ms	remaining: 45.4s
30:	total: 558ms	remaining: 35.5s
46:	total: 557ms	remaining: 23.2s
31:	total: 567ms	remaining: 34.8s
32:	total: 575ms	remaining: 34.3s
47:	total: 573ms	remaining: 23.3s
23:	total: 555ms	remaining: 45.7s
33:	total: 587ms	remaining: 33.9s
24:	total: 572ms	remaining: 45.2s
48:	total: 593ms	remaining: 23.6s
34:	total: 602ms	remaining: 33.8s
35:	total: 615ms	remaining: 33.6s
25:	total: 597ms	remaining: 45.3s
49:	total: 617ms	remaining: 24.1s
36:	total: 628ms	remaining: 33.3s
50:	total: 633ms	remaining: 24.2s
26:	total: 619ms	remaining: 45.2s
37:	total: 641ms	remaining: 33.1s
51:	total: 652ms	remaining: 24.4s
38:	total: 655ms	remaining: 32.9s
27:	total: 640ms	remaining: 45.1s
39:	total: 665ms	remaining: 32.6s
52:	total: 665ms	remaining: 24.4s
28:	total: 656ms	remaining: 44.6s
40:	total: 678ms	remaining: 32.4s
53:	total: 685ms	remaining: 24.7s
41:	total: 689ms	remaining: 32.1s
29:	total: 674ms	remaining: 44.3s
42:	total: 699ms	remaining: 31.8s
54:	total: 703ms	remaining: 24.8s
43:	total: 709ms	remaining: 31.5s
30:	total: 697ms	remaining: 44.3s
44:	total: 717ms	remaining: 31.1s
31:	total: 704ms	remaining: 43.3s
55:	total: 726ms	remaining: 25.2s
45:	total: 728ms	remaining: 30.9s
32:	total: 711ms	remaining: 42.4s
46:	total: 737ms	remaining: 30.6s
33:	total: 719ms	remaining: 41.6s
47:	total: 745ms	remaining: 30.3s
56:	total: 752ms	remaining: 25.6s
48:	total: 754ms	remaining: 30s
34:	total: 736ms	remaining: 41.3s
49:	total: 761ms	remaining: 29.7s
50:	total: 772ms	remaining: 29.5s
57:	total: 777ms	remaining: 26s
35:	total: 759ms	remaining: 41.4s
51:	total: 781ms	remaining: 29.2s
52:	total: 789ms	remaining: 29s
53:	total: 798ms	remaining: 28.8s
36:	total: 782ms	remaining: 41.5s
58:	total: 804ms	remaining: 26.4s
54:	total: 815ms	remaining: 28.8s
37:	total: 801ms	remaining: 41.3s
59:	total: 824ms	remaining: 26.6s
55:	total: 831ms	remaining: 28.9s
38:	total: 823ms	remaining: 41.4s
56:	total: 844ms	remaining: 28.8s
60:	total: 846ms	remaining: 26.9s
57:	total: 855ms	remaining: 28.6s
39:	total: 843ms	remaining: 41.3s
58:	total: 866ms	remaining: 28.5s
61:	total: 866ms	remaining: 27.1s
40:	total: 859ms	remaining: 41s
59:	total: 879ms	remaining: 28.4s
60:	total: 889ms	remaining: 28.2s
62:	total: 890ms	remaining: 27.4s
41:	total: 879ms	remaining: 41s
61:	total: 898ms	remaining: 28.1s
62:	total: 908ms	remaining: 27.9s
42:	total: 893ms	remaining: 40.6s
63:	total: 915ms	remaining: 27.7s
63:	total: 921ms	remaining: 27.8s
43:	total: 905ms	remaining: 40.2s
64:	total: 933ms	remaining: 27.8s
44:	total: 925ms	remaining: 40.2s
64:	total: 947ms	remaining: 28.2s
65:	total: 948ms	remaining: 27.8s
66:	total: 960ms	remaining: 27.7s
45:	total: 955ms	remaining: 40.6s
65:	total: 977ms	remaining: 28.6s
67:	total: 981ms	remaining: 27.9s
46:	total: 974ms	remaining: 40.5s
68:	total: 997ms	remaining: 27.9s
66:	total: 1.01s	remaining: 29s
69:	total: 1.01s	remaining: 27.8s
47:	total: 991ms	remaining: 40.3s
70:	total: 1.01s	remaining: 27.6s
48:	total: 1s	remaining: 39.9s
71:	total: 1.02s	remaining: 27.4s
67:	total: 1.03s	remaining: 29.3s
72:	total: 1.03s	remaining: 27.2s
49:	total: 1.02s	remaining: 39.9s
73:	total: 1.04s	remaining: 27.1s
74:	total: 1.04s	remaining: 26.8s
75:	total: 1.05s	remaining: 26.6s
76:	total: 1.06s	remaining: 26.4s
50:	total: 1.04s	remaining: 39.7s
68:	total: 1.06s	remaining: 29.8s
77:	total: 1.06s	remaining: 26.2s
78:	total: 1.07s	remaining: 26s
79:	total: 1.07s	remaining: 25.7s
80:	total: 1.07s	remaining: 25.5s
81:	total: 1.08s	remaining: 25.2s
82:	total: 1.08s	remaining: 25.1s
69:	total: 1.09s	remaining: 30.1s
51:	total: 1.07s	remaining: 40.2s
83:	total: 1.09s	remaining: 24.9s
52:	total: 1.09s	remaining: 39.9s
70:	total: 1.11s	remaining: 30.2s
84:	total: 1.11s	remaining: 25s
53:	total: 1.1s	remaining: 39.5s
85:	total: 1.12s	remaining: 25s
54:	total: 1.11s	remaining: 39.2s
71:	total: 1.13s	remaining: 30.3s
55:	total: 1.11s	remaining: 38.6s
56:	total: 1.12s	remaining: 38.1s
86:	total: 1.13s	remaining: 24.9s
57:	total: 1.12s	remaining: 37.5s
58:	total: 1.13s	remaining: 37s
87:	total: 1.14s	remaining: 24.8s
59:	total: 1.13s	remaining: 36.5s
88:	total: 1.15s	remaining: 24.6s
60:	total: 1.13s	remaining: 36s
72:	total: 1.16s	remaining: 30.5s
89:	total: 1.15s	remaining: 24.5s
61:	total: 1.14s	remaining: 35.6s
90:	total: 1.16s	remaining: 24.3s
62:	total: 1.14s	remaining: 35.2s
91:	total: 1.17s	remaining: 24.2s
63:	total: 1.15s	remaining: 34.9s
92:	total: 1.17s	remaining: 24.1s
93:	total: 1.18s	remaining: 23.9s
73:	total: 1.19s	remaining: 30.9s
64:	total: 1.17s	remaining: 34.7s
94:	total: 1.18s	remaining: 23.7s
95:	total: 1.19s	remaining: 23.6s
65:	total: 1.18s	remaining: 34.6s
96:	total: 1.2s	remaining: 23.6s
97:	total: 1.21s	remaining: 23.4s
66:	total: 1.19s	remaining: 34.3s
98:	total: 1.21s	remaining: 23.3s
74:	total: 1.22s	remaining: 31.2s
99:	total: 1.22s	remaining: 23.1s
67:	total: 1.2s	remaining: 34.1s
100:	total: 1.22s	remaining: 23s
101:	total: 1.23s	remaining: 22.8s
68:	total: 1.21s	remaining: 33.9s
102:	total: 1.23s	remaining: 22.7s
69:	total: 1.22s	remaining: 33.7s
103:	total: 1.24s	remaining: 22.6s
104:	total: 1.24s	remaining: 22.4s
70:	total: 1.23s	remaining: 33.4s
75:	total: 1.25s	remaining: 31.7s
105:	total: 1.25s	remaining: 22.4s
71:	total: 1.24s	remaining: 33.3s
106:	total: 1.27s	remaining: 22.5s
76:	total: 1.28s	remaining: 31.9s
72:	total: 1.26s	remaining: 33.2s
107:	total: 1.28s	remaining: 22.4s
108:	total: 1.28s	remaining: 22.3s
73:	total: 1.27s	remaining: 33.1s
74:	total: 1.28s	remaining: 33s
109:	total: 1.3s	remaining: 22.3s
77:	total: 1.31s	remaining: 32.3s
75:	total: 1.29s	remaining: 32.8s
110:	total: 1.31s	remaining: 22.3s
111:	total: 1.32s	remaining: 22.3s
76:	total: 1.31s	remaining: 32.8s
78:	total: 1.33s	remaining: 32.4s
112:	total: 1.33s	remaining: 22.2s
113:	total: 1.34s	remaining: 22.2s
77:	total: 1.33s	remaining: 32.7s
79:	total: 1.35s	remaining: 32.4s
114:	total: 1.35s	remaining: 22.1s
78:	total: 1.34s	remaining: 32.6s
115:	total: 1.36s	remaining: 22.1s
80:	total: 1.37s	remaining: 32.5s
116:	total: 1.36s	remaining: 22s
117:	total: 1.37s	remaining: 21.9s
79:	total: 1.36s	remaining: 32.6s
81:	total: 1.38s	remaining: 32.3s
118:	total: 1.38s	remaining: 21.8s
80:	total: 1.37s	remaining: 32.5s
119:	total: 1.39s	remaining: 21.8s
82:	total: 1.4s	remaining: 32.3s
120:	total: 1.4s	remaining: 21.8s
81:	total: 1.39s	remaining: 32.5s
121:	total: 1.41s	remaining: 21.7s
83:	total: 1.42s	remaining: 32.3s
82:	total: 1.4s	remaining: 32.3s
83:	total: 1.41s	remaining: 32.2s
122:	total: 1.43s	remaining: 21.9s
84:	total: 1.44s	remaining: 32.4s
84:	total: 1.43s	remaining: 32.1s
123:	total: 1.44s	remaining: 21.8s
124:	total: 1.45s	remaining: 21.8s
85:	total: 1.46s	remaining: 32.4s
85:	total: 1.44s	remaining: 32.2s
125:	total: 1.46s	remaining: 21.8s
86:	total: 1.47s	remaining: 32.4s
86:	total: 1.46s	remaining: 32.1s
126:	total: 1.48s	remaining: 21.8s
87:	total: 1.49s	remaining: 32.3s
87:	total: 1.48s	remaining: 32.1s
127:	total: 1.49s	remaining: 21.8s
88:	total: 1.5s	remaining: 32.2s
89:	total: 1.51s	remaining: 32.1s
128:	total: 1.51s	remaining: 21.9s
88:	total: 1.5s	remaining: 32.1s
90:	total: 1.53s	remaining: 32s
129:	total: 1.53s	remaining: 22s
89:	total: 1.51s	remaining: 32.2s
91:	total: 1.54s	remaining: 32s
90:	total: 1.53s	remaining: 32.1s
130:	total: 1.54s	remaining: 22s
92:	total: 1.55s	remaining: 31.8s
91:	total: 1.54s	remaining: 32s
93:	total: 1.56s	remaining: 31.7s
94:	total: 1.57s	remaining: 31.5s
92:	total: 1.55s	remaining: 31.8s
131:	total: 1.57s	remaining: 22.2s
95:	total: 1.58s	remaining: 31.3s
93:	total: 1.56s	remaining: 31.7s
96:	total: 1.59s	remaining: 31.1s
132:	total: 1.59s	remaining: 22.3s
94:	total: 1.58s	remaining: 31.6s
97:	total: 1.6s	remaining: 31s
95:	total: 1.59s	remaining: 31.6s
133:	total: 1.6s	remaining: 22.3s
98:	total: 1.61s	remaining: 30.9s
96:	total: 1.6s	remaining: 31.5s
134:	total: 1.62s	remaining: 22.4s
99:	total: 1.63s	remaining: 30.9s
97:	total: 1.62s	remaining: 31.4s
135:	total: 1.64s	remaining: 22.4s
100:	total: 1.65s	remaining: 31s
98:	total: 1.63s	remaining: 31.3s
136:	total: 1.65s	remaining: 22.4s
99:	total: 1.64s	remaining: 31.2s
101:	total: 1.66s	remaining: 30.9s
137:	total: 1.66s	remaining: 22.4s
102:	total: 1.68s	remaining: 30.8s
100:	total: 1.66s	remaining: 31.2s
138:	total: 1.68s	remaining: 22.4s
103:	total: 1.69s	remaining: 30.8s
101:	total: 1.67s	remaining: 31.2s
139:	total: 1.69s	remaining: 22.4s
102:	total: 1.69s	remaining: 31.1s
140:	total: 1.7s	remaining: 22.4s
104:	total: 1.71s	remaining: 30.9s
103:	total: 1.7s	remaining: 31s
141:	total: 1.72s	remaining: 22.5s
104:	total: 1.71s	remaining: 30.9s
105:	total: 1.73s	remaining: 31s
105:	total: 1.73s	remaining: 30.8s
142:	total: 1.74s	remaining: 22.6s
106:	total: 1.75s	remaining: 30.9s
107:	total: 1.75s	remaining: 30.7s
106:	total: 1.74s	remaining: 30.8s
143:	total: 1.75s	remaining: 22.6s
108:	total: 1.77s	remaining: 30.8s
144:	total: 1.77s	remaining: 22.6s
107:	total: 1.76s	remaining: 30.8s
145:	total: 1.78s	remaining: 22.6s
109:	total: 1.79s	remaining: 30.7s
146:	total: 1.78s	remaining: 22.5s
108:	total: 1.77s	remaining: 30.8s
147:	total: 1.79s	remaining: 22.4s
148:	total: 1.79s	remaining: 22.3s
110:	total: 1.8s	remaining: 30.7s
109:	total: 1.79s	remaining: 30.7s
149:	total: 1.8s	remaining: 22.2s
150:	total: 1.81s	remaining: 22.1s
111:	total: 1.82s	remaining: 30.7s
110:	total: 1.8s	remaining: 30.7s
151:	total: 1.81s	remaining: 22.1s
152:	total: 1.82s	remaining: 22s
153:	total: 1.83s	remaining: 21.9s
111:	total: 1.82s	remaining: 30.7s
112:	total: 1.84s	remaining: 30.7s
154:	total: 1.83s	remaining: 21.8s
155:	total: 1.84s	remaining: 21.7s
113:	total: 1.85s	remaining: 30.6s
112:	total: 1.84s	remaining: 30.7s
156:	total: 1.85s	remaining: 21.7s
157:	total: 1.86s	remaining: 21.6s
113:	total: 1.85s	remaining: 30.6s
114:	total: 1.87s	remaining: 30.7s
158:	total: 1.86s	remaining: 21.6s
159:	total: 1.87s	remaining: 21.5s
160:	total: 1.87s	remaining: 21.4s
115:	total: 1.89s	remaining: 30.6s
114:	total: 1.87s	remaining: 30.6s
161:	total: 1.88s	remaining: 21.3s
162:	total: 1.89s	remaining: 21.3s
115:	total: 1.88s	remaining: 30.6s
116:	total: 1.9s	remaining: 30.6s
163:	total: 1.9s	remaining: 21.3s
116:	total: 1.9s	remaining: 30.5s
164:	total: 1.91s	remaining: 21.2s
117:	total: 1.92s	remaining: 30.7s
117:	total: 1.91s	remaining: 30.4s
165:	total: 1.92s	remaining: 21.2s
118:	total: 1.94s	remaining: 30.6s
166:	total: 1.93s	remaining: 21.2s
118:	total: 1.92s	remaining: 30.4s
167:	total: 1.94s	remaining: 21.1s
119:	total: 1.93s	remaining: 30.3s
119:	total: 1.95s	remaining: 30.6s
168:	total: 1.95s	remaining: 21.1s
169:	total: 1.95s	remaining: 21s
120:	total: 1.97s	remaining: 30.5s
120:	total: 1.95s	remaining: 30.3s
170:	total: 1.96s	remaining: 20.9s
171:	total: 1.97s	remaining: 20.9s
121:	total: 1.98s	remaining: 30.5s
121:	total: 1.97s	remaining: 30.3s
172:	total: 1.97s	remaining: 20.9s
173:	total: 1.99s	remaining: 20.8s
122:	total: 2s	remaining: 30.6s
122:	total: 1.99s	remaining: 30.3s
174:	total: 1.99s	remaining: 20.8s
175:	total: 2s	remaining: 20.8s
123:	total: 2.02s	remaining: 30.6s
123:	total: 2s	remaining: 30.3s
176:	total: 2.02s	remaining: 20.8s
124:	total: 2.04s	remaining: 30.5s
124:	total: 2.02s	remaining: 30.3s
177:	total: 2.02s	remaining: 20.7s
178:	total: 2.04s	remaining: 20.7s
125:	total: 2.05s	remaining: 30.5s
125:	total: 2.03s	remaining: 30.3s
179:	total: 2.05s	remaining: 20.7s
126:	total: 2.06s	remaining: 30.4s
126:	total: 2.05s	remaining: 30.2s
180:	total: 2.06s	remaining: 20.7s
127:	total: 2.08s	remaining: 30.4s
181:	total: 2.07s	remaining: 20.6s
127:	total: 2.06s	remaining: 30.2s
182:	total: 2.08s	remaining: 20.6s
128:	total: 2.1s	remaining: 30.4s
128:	total: 2.08s	remaining: 30.2s
129:	total: 2.1s	remaining: 30.3s
130:	total: 2.11s	remaining: 30.1s
183:	total: 2.09s	remaining: 20.7s
131:	total: 2.11s	remaining: 29.9s
132:	total: 2.12s	remaining: 29.7s
129:	total: 2.1s	remaining: 30.2s
133:	total: 2.12s	remaining: 29.5s
134:	total: 2.12s	remaining: 29.3s
184:	total: 2.11s	remaining: 20.7s
135:	total: 2.13s	remaining: 29.2s
130:	total: 2.11s	remaining: 30.1s
136:	total: 2.14s	remaining: 29.1s
185:	total: 2.13s	remaining: 20.8s
131:	total: 2.13s	remaining: 30.1s
137:	total: 2.15s	remaining: 29s
132:	total: 2.14s	remaining: 30s
138:	total: 2.16s	remaining: 28.9s
186:	total: 2.15s	remaining: 20.9s
133:	total: 2.15s	remaining: 29.9s
134:	total: 2.15s	remaining: 29.7s
139:	total: 2.17s	remaining: 28.9s
135:	total: 2.16s	remaining: 29.6s
136:	total: 2.16s	remaining: 29.4s
187:	total: 2.17s	remaining: 20.9s
140:	total: 2.19s	remaining: 28.8s
141:	total: 2.19s	remaining: 28.7s
137:	total: 2.18s	remaining: 29.4s
138:	total: 2.18s	remaining: 29.2s
142:	total: 2.2s	remaining: 28.6s
188:	total: 2.19s	remaining: 21s
143:	total: 2.21s	remaining: 28.5s
139:	total: 2.19s	remaining: 29.2s
144:	total: 2.22s	remaining: 28.4s
189:	total: 2.21s	remaining: 21s
140:	total: 2.21s	remaining: 29.1s
145:	total: 2.24s	remaining: 28.4s
141:	total: 2.22s	remaining: 29.1s
190:	total: 2.23s	remaining: 21.1s
142:	total: 2.23s	remaining: 29s
146:	total: 2.25s	remaining: 28.4s
191:	total: 2.24s	remaining: 21.1s
147:	total: 2.27s	remaining: 28.4s
192:	total: 2.26s	remaining: 21.1s
143:	total: 2.25s	remaining: 29s
148:	total: 2.28s	remaining: 28.3s
144:	total: 2.27s	remaining: 29s
149:	total: 2.29s	remaining: 28.2s
193:	total: 2.27s	remaining: 21.2s
194:	total: 2.28s	remaining: 21.1s
195:	total: 2.29s	remaining: 21s
150:	total: 2.3s	remaining: 28.2s
145:	total: 2.29s	remaining: 29s
151:	total: 2.31s	remaining: 28.1s
196:	total: 2.3s	remaining: 21s
152:	total: 2.31s	remaining: 27.9s
153:	total: 2.32s	remaining: 27.8s
146:	total: 2.31s	remaining: 29.1s
154:	total: 2.33s	remaining: 27.7s
197:	total: 2.31s	remaining: 21.1s
147:	total: 2.32s	remaining: 29s
198:	total: 2.33s	remaining: 21s
155:	total: 2.34s	remaining: 27.7s
148:	total: 2.33s	remaining: 28.9s
199:	total: 2.34s	remaining: 21.1s
156:	total: 2.35s	remaining: 27.6s
149:	total: 2.34s	remaining: 28.9s
157:	total: 2.37s	remaining: 27.6s
200:	total: 2.35s	remaining: 21.1s
150:	total: 2.35s	remaining: 28.8s
158:	total: 2.37s	remaining: 27.5s
151:	total: 2.36s	remaining: 28.7s
201:	total: 2.37s	remaining: 21.1s
152:	total: 2.37s	remaining: 28.6s
159:	total: 2.39s	remaining: 27.5s
202:	total: 2.38s	remaining: 21.1s
153:	total: 2.38s	remaining: 28.6s
160:	total: 2.4s	remaining: 27.5s
203:	total: 2.39s	remaining: 21.1s
154:	total: 2.4s	remaining: 28.5s
161:	total: 2.42s	remaining: 27.4s
204:	total: 2.41s	remaining: 21.1s
155:	total: 2.41s	remaining: 28.5s
205:	total: 2.42s	remaining: 21.1s
162:	total: 2.43s	remaining: 27.4s
206:	total: 2.43s	remaining: 21.1s
163:	total: 2.44s	remaining: 27.4s
156:	total: 2.43s	remaining: 28.5s
207:	total: 2.44s	remaining: 21.1s
164:	total: 2.46s	remaining: 27.4s
208:	total: 2.45s	remaining: 21s
157:	total: 2.45s	remaining: 28.5s
209:	total: 2.46s	remaining: 20.9s
210:	total: 2.46s	remaining: 20.9s
165:	total: 2.47s	remaining: 27.3s
211:	total: 2.46s	remaining: 20.8s
212:	total: 2.47s	remaining: 20.7s
158:	total: 2.46s	remaining: 28.5s
213:	total: 2.48s	remaining: 20.7s
166:	total: 2.49s	remaining: 27.4s
214:	total: 2.49s	remaining: 20.6s
159:	total: 2.49s	remaining: 28.6s
167:	total: 2.51s	remaining: 27.4s
215:	total: 2.5s	remaining: 20.6s
168:	total: 2.53s	remaining: 27.4s
160:	total: 2.51s	remaining: 28.7s
216:	total: 2.51s	remaining: 20.6s
217:	total: 2.52s	remaining: 20.6s
169:	total: 2.54s	remaining: 27.4s
161:	total: 2.53s	remaining: 28.7s
218:	total: 2.54s	remaining: 20.6s
162:	total: 2.54s	remaining: 28.7s
219:	total: 2.55s	remaining: 20.6s
170:	total: 2.57s	remaining: 27.4s
220:	total: 2.56s	remaining: 20.6s
163:	total: 2.56s	remaining: 28.6s
221:	total: 2.56s	remaining: 20.5s
171:	total: 2.58s	remaining: 27.5s
164:	total: 2.57s	remaining: 28.6s
222:	total: 2.58s	remaining: 20.5s
223:	total: 2.59s	remaining: 20.5s
172:	total: 2.6s	remaining: 27.5s
165:	total: 2.59s	remaining: 28.6s
224:	total: 2.6s	remaining: 20.5s
166:	total: 2.6s	remaining: 28.5s
173:	total: 2.62s	remaining: 27.5s
225:	total: 2.61s	remaining: 20.5s
167:	total: 2.61s	remaining: 28.5s
226:	total: 2.62s	remaining: 20.5s
168:	total: 2.63s	remaining: 28.5s
174:	total: 2.65s	remaining: 27.6s
227:	total: 2.64s	remaining: 20.5s
169:	total: 2.64s	remaining: 28.4s
175:	total: 2.67s	remaining: 27.7s
170:	total: 2.65s	remaining: 28.4s
228:	total: 2.66s	remaining: 20.6s
171:	total: 2.67s	remaining: 28.4s
229:	total: 2.67s	remaining: 20.6s
176:	total: 2.7s	remaining: 27.8s
172:	total: 2.68s	remaining: 28.3s
230:	total: 2.68s	remaining: 20.5s
173:	total: 2.69s	remaining: 28.2s
231:	total: 2.7s	remaining: 20.5s
177:	total: 2.71s	remaining: 27.8s

0.9833977085460472

In [294]:
model = cb

model.fit(X_train, y_train)

0:	total: 22.1ms	remaining: 44.1s
1:	total: 49.8ms	remaining: 49.8s
2:	total: 68.4ms	remaining: 45.5s
3:	total: 82ms	remaining: 40.9s
4:	total: 93.5ms	remaining: 37.3s
5:	total: 107ms	remaining: 35.6s
6:	total: 114ms	remaining: 32.5s
7:	total: 119ms	remaining: 29.8s
8:	total: 124ms	remaining: 27.5s
9:	total: 129ms	remaining: 25.7s
10:	total: 133ms	remaining: 24.1s
11:	total: 137ms	remaining: 22.8s
12:	total: 142ms	remaining: 21.6s
13:	total: 146ms	remaining: 20.7s
14:	total: 151ms	remaining: 20s
15:	total: 156ms	remaining: 19.4s
16:	total: 161ms	remaining: 18.8s
17:	total: 166ms	remaining: 18.3s
18:	total: 171ms	remaining: 17.8s
19:	total: 176ms	remaining: 17.4s
20:	total: 183ms	remaining: 17.3s
21:	total: 191ms	remaining: 17.2s
22:	total: 197ms	remaining: 16.9s
23:	total: 202ms	remaining: 16.6s
24:	total: 206ms	remaining: 16.3s
25:	total: 211ms	remaining: 16s
26:	total: 216ms	remaining: 15.8s
27:	total: 222ms	remaining: 15.6s
28:	total: 231ms	remaining: 15.7s
29:	total: 236ms	remaining: 15.5s
30:	total: 241ms	remaining: 15.3s
31:	total: 246ms	remaining: 15.1s
32:	total: 252ms	remaining: 15s
33:	total: 260ms	remaining: 15s
34:	total: 268ms	remaining: 15s
35:	total: 278ms	remaining: 15.2s
36:	total: 287ms	remaining: 15.2s
37:	total: 297ms	remaining: 15.3s
38:	total: 301ms	remaining: 15.2s
39:	total: 306ms	remaining: 15s
40:	total: 311ms	remaining: 14.9s
41:	total: 319ms	remaining: 14.9s
42:	total: 324ms	remaining: 14.8s
43:	total: 330ms	remaining: 14.7s
44:	total: 335ms	remaining: 14.6s
45:	total: 340ms	remaining: 14.4s
46:	total: 344ms	remaining: 14.3s
47:	total: 351ms	remaining: 14.3s
48:	total: 357ms	remaining: 14.2s
49:	total: 361ms	remaining: 14.1s
50:	total: 370ms	remaining: 14.1s
51:	total: 376ms	remaining: 14.1s
52:	total: 386ms	remaining: 14.2s
53:	total: 393ms	remaining: 14.1s
54:	total: 398ms	remaining: 14.1s
55:	total: 403ms	remaining: 14s
56:	total: 408ms	remaining: 13.9s
57:	total: 414ms	remaining: 13.9s
58:	total: 424ms	remaining: 14s
59:	total: 431ms	remaining: 13.9s
60:	total: 438ms	remaining: 13.9s
61:	total: 443ms	remaining: 13.8s
62:	total: 452ms	remaining: 13.9s
63:	total: 459ms	remaining: 13.9s
64:	total: 464ms	remaining: 13.8s
65:	total: 469ms	remaining: 13.7s
66:	total: 474ms	remaining: 13.7s
67:	total: 479ms	remaining: 13.6s
68:	total: 486ms	remaining: 13.6s
69:	total: 491ms	remaining: 13.5s
70:	total: 496ms	remaining: 13.5s
71:	total: 501ms	remaining: 13.4s
72:	total: 508ms	remaining: 13.4s
73:	total: 521ms	remaining: 13.6s
74:	total: 529ms	remaining: 13.6s
75:	total: 537ms	remaining: 13.6s
76:	total: 546ms	remaining: 13.6s
77:	total: 554ms	remaining: 13.6s
78:	total: 558ms	remaining: 13.6s
79:	total: 562ms	remaining: 13.5s
80:	total: 566ms	remaining: 13.4s
81:	total: 570ms	remaining: 13.3s
82:	total: 574ms	remaining: 13.3s
83:	total: 579ms	remaining: 13.2s
84:	total: 584ms	remaining: 13.2s
85:	total: 590ms	remaining: 13.1s
86:	total: 595ms	remaining: 13.1s
87:	total: 599ms	remaining: 13s
88:	total: 603ms	remaining: 13s
89:	total: 608ms	remaining: 12.9s
90:	total: 612ms	remaining: 12.8s
91:	total: 616ms	remaining: 12.8s
92:	total: 620ms	remaining: 12.7s
93:	total: 624ms	remaining: 12.7s
94:	total: 629ms	remaining: 12.6s
95:	total: 633ms	remaining: 12.6s
96:	total: 638ms	remaining: 12.5s
97:	total: 643ms	remaining: 12.5s
98:	total: 648ms	remaining: 12.4s
99:	total: 652ms	remaining: 12.4s
100:	total: 656ms	remaining: 12.3s
101:	total: 660ms	remaining: 12.3s
102:	total: 665ms	remaining: 12.2s
103:	total: 669ms	remaining: 12.2s
104:	total: 674ms	remaining: 12.2s
105:	total: 679ms	remaining: 12.1s
106:	total: 684ms	remaining: 12.1s
107:	total: 689ms	remaining: 12.1s
108:	total: 693ms	remaining: 12s
109:	total: 697ms	remaining: 12s
110:	total: 701ms	remaining: 11.9s
111:	total: 706ms	remaining: 11.9s
112:	total: 714ms	remaining: 11.9s
113:	total: 722ms	remaining: 11.9s
114:	total: 726ms	remaining: 11.9s
115:	total: 731ms	remaining: 11.9s
116:	total: 735ms	remaining: 11.8s
117:	total: 741ms	remaining: 11.8s
118:	total: 746ms	remaining: 11.8s
119:	total: 752ms	remaining: 11.8s
120:	total: 757ms	remaining: 11.8s
121:	total: 762ms	remaining: 11.7s
122:	total: 766ms	remaining: 11.7s
123:	total: 771ms	remaining: 11.7s
124:	total: 778ms	remaining: 11.7s
125:	total: 782ms	remaining: 11.6s
126:	total: 786ms	remaining: 11.6s
127:	total: 791ms	remaining: 11.6s
128:	total: 797ms	remaining: 11.6s
129:	total: 801ms	remaining: 11.5s
130:	total: 808ms	remaining: 11.5s
131:	total: 813ms	remaining: 11.5s
132:	total: 817ms	remaining: 11.5s
133:	total: 821ms	remaining: 11.4s
134:	total: 826ms	remaining: 11.4s
135:	total: 831ms	remaining: 11.4s
136:	total: 837ms	remaining: 11.4s
137:	total: 842ms	remaining: 11.4s
138:	total: 846ms	remaining: 11.3s
139:	total: 851ms	remaining: 11.3s
140:	total: 855ms	remaining: 11.3s
141:	total: 860ms	remaining: 11.3s
142:	total: 865ms	remaining: 11.2s
143:	total: 870ms	remaining: 11.2s
144:	total: 876ms	remaining: 11.2s
145:	total: 881ms	remaining: 11.2s
146:	total: 886ms	remaining: 11.2s
147:	total: 890ms	remaining: 11.1s
148:	total: 896ms	remaining: 11.1s
149:	total: 901ms	remaining: 11.1s
150:	total: 906ms	remaining: 11.1s
151:	total: 913ms	remaining: 11.1s
152:	total: 918ms	remaining: 11.1s
153:	total: 922ms	remaining: 11.1s
154:	total: 926ms	remaining: 11s
155:	total: 931ms	remaining: 11s
156:	total: 937ms	remaining: 11s
157:	total: 941ms	remaining: 11s
158:	total: 946ms	remaining: 11s
159:	total: 951ms	remaining: 10.9s
160:	total: 956ms	remaining: 10.9s
161:	total: 960ms	remaining: 10.9s
162:	total: 966ms	remaining: 10.9s
163:	total: 971ms	remaining: 10.9s
164:	total: 976ms	remaining: 10.9s
165:	total: 981ms	remaining: 10.8s
166:	total: 985ms	remaining: 10.8s
167:	total: 993ms	remaining: 10.8s
168:	total: 999ms	remaining: 10.8s
169:	total: 1s	remaining: 10.8s
170:	total: 1.01s	remaining: 10.8s
171:	total: 1.01s	remaining: 10.8s
172:	total: 1.02s	remaining: 10.8s
173:	total: 1.02s	remaining: 10.7s
174:	total: 1.03s	remaining: 10.7s
175:	total: 1.03s	remaining: 10.7s
176:	total: 1.04s	remaining: 10.7s
177:	total: 1.04s	remaining: 10.7s
178:	total: 1.05s	remaining: 10.7s
179:	total: 1.05s	remaining: 10.6s
180:	total: 1.06s	remaining: 10.6s
181:	total: 1.06s	remaining: 10.6s
182:	total: 1.07s	remaining: 10.6s
183:	total: 1.08s	remaining: 10.6s
184:	total: 1.08s	remaining: 10.6s
185:	total: 1.08s	remaining: 10.6s
186:	total: 1.09s	remaining: 10.6s
187:	total: 1.1s	remaining: 10.6s
188:	total: 1.1s	remaining: 10.6s
189:	total: 1.11s	remaining: 10.6s
190:	total: 1.11s	remaining: 10.5s
191:	total: 1.12s	remaining: 10.5s
192:	total: 1.12s	remaining: 10.5s
193:	total: 1.13s	remaining: 10.5s
194:	total: 1.13s	remaining: 10.5s
195:	total: 1.14s	remaining: 10.5s
196:	total: 1.14s	remaining: 10.5s
197:	total: 1.15s	remaining: 10.5s
198:	total: 1.16s	remaining: 10.5s
199:	total: 1.16s	remaining: 10.5s
200:	total: 1.17s	remaining: 10.4s
201:	total: 1.17s	remaining: 10.4s
202:	total: 1.18s	remaining: 10.4s
203:	total: 1.18s	remaining: 10.4s
204:	total: 1.19s	remaining: 10.4s
205:	total: 1.19s	remaining: 10.4s
206:	total: 1.2s	remaining: 10.4s
207:	total: 1.2s	remaining: 10.4s
208:	total: 1.21s	remaining: 10.4s
209:	total: 1.21s	remaining: 10.3s
210:	total: 1.22s	remaining: 10.3s
211:	total: 1.23s	remaining: 10.3s
212:	total: 1.23s	remaining: 10.3s
213:	total: 1.24s	remaining: 10.3s
214:	total: 1.24s	remaining: 10.3s
215:	total: 1.25s	remaining: 10.3s
216:	total: 1.25s	remaining: 10.3s
217:	total: 1.26s	remaining: 10.3s
218:	total: 1.26s	remaining: 10.3s
219:	total: 1.27s	remaining: 10.3s
220:	total: 1.27s	remaining: 10.3s
221:	total: 1.28s	remaining: 10.3s
222:	total: 1.29s	remaining: 10.3s
223:	total: 1.29s	remaining: 10.2s
224:	total: 1.3s	remaining: 10.2s
225:	total: 1.3s	remaining: 10.2s
226:	total: 1.3s	remaining: 10.2s
227:	total: 1.31s	remaining: 10.2s
228:	total: 1.31s	remaining: 10.2s
229:	total: 1.32s	remaining: 10.2s
230:	total: 1.32s	remaining: 10.2s
231:	total: 1.33s	remaining: 10.1s
232:	total: 1.33s	remaining: 10.1s
233:	total: 1.34s	remaining: 10.1s
234:	total: 1.35s	remaining: 10.1s
235:	total: 1.35s	remaining: 10.1s
236:	total: 1.36s	remaining: 10.1s
237:	total: 1.36s	remaining: 10.1s
238:	total: 1.37s	remaining: 10.1s
239:	total: 1.37s	remaining: 10.1s
240:	total: 1.38s	remaining: 10s
241:	total: 1.38s	remaining: 10s
242:	total: 1.39s	remaining: 10s
243:	total: 1.39s	remaining: 10s
244:	total: 1.4s	remaining: 10s
245:	total: 1.4s	remaining: 10s
246:	total: 1.41s	remaining: 10s
247:	total: 1.42s	remaining: 10s
248:	total: 1.43s	remaining: 10s
249:	total: 1.43s	remaining: 10s
250:	total: 1.44s	remaining: 10s
251:	total: 1.44s	remaining: 10s
252:	total: 1.45s	remaining: 10s
253:	total: 1.45s	remaining: 9.99s
254:	total: 1.46s	remaining: 9.98s
255:	total: 1.46s	remaining: 9.96s
256:	total: 1.47s	remaining: 9.95s
257:	total: 1.47s	remaining: 9.94s
258:	total: 1.48s	remaining: 9.94s
259:	total: 1.48s	remaining: 9.92s
260:	total: 1.49s	remaining: 9.9s
261:	total: 1.49s	remaining: 9.9s
262:	total: 1.5s	remaining: 9.88s
263:	total: 1.5s	remaining: 9.88s
264:	total: 1.51s	remaining: 9.87s
265:	total: 1.51s	remaining: 9.85s
266:	total: 1.52s	remaining: 9.84s
267:	total: 1.52s	remaining: 9.83s
268:	total: 1.52s	remaining: 9.81s
269:	total: 1.53s	remaining: 9.79s
270:	total: 1.53s	remaining: 9.78s
271:	total: 1.54s	remaining: 9.78s
272:	total: 1.54s	remaining: 9.77s
273:	total: 1.55s	remaining: 9.76s
274:	total: 1.55s	remaining: 9.75s
275:	total: 1.56s	remaining: 9.76s
276:	total: 1.57s	remaining: 9.75s
277:	total: 1.57s	remaining: 9.75s
278:	total: 1.58s	remaining: 9.74s
279:	total: 1.58s	remaining: 9.73s
280:	total: 1.59s	remaining: 9.72s
281:	total: 1.59s	remaining: 9.72s
282:	total: 1.6s	remaining: 9.73s
283:	total: 1.61s	remaining: 9.72s
284:	total: 1.61s	remaining: 9.7s
285:	total: 1.62s	remaining: 9.69s
286:	total: 1.62s	remaining: 9.68s
287:	total: 1.63s	remaining: 9.67s
288:	total: 1.63s	remaining: 9.65s
289:	total: 1.64s	remaining: 9.65s
290:	total: 1.64s	remaining: 9.64s
291:	total: 1.65s	remaining: 9.63s
292:	total: 1.65s	remaining: 9.62s
293:	total: 1.66s	remaining: 9.61s
294:	total: 1.66s	remaining: 9.61s
295:	total: 1.67s	remaining: 9.61s
296:	total: 1.67s	remaining: 9.6s
297:	total: 1.68s	remaining: 9.59s
298:	total: 1.68s	remaining: 9.58s
299:	total: 1.69s	remaining: 9.57s
300:	total: 1.69s	remaining: 9.56s
301:	total: 1.7s	remaining: 9.56s
302:	total: 1.71s	remaining: 9.57s
303:	total: 1.71s	remaining: 9.56s
304:	total: 1.72s	remaining: 9.55s
305:	total: 1.72s	remaining: 9.54s
306:	total: 1.73s	remaining: 9.53s
307:	total: 1.73s	remaining: 9.53s
308:	total: 1.74s	remaining: 9.52s
309:	total: 1.74s	remaining: 9.51s
310:	total: 1.75s	remaining: 9.5s
311:	total: 1.75s	remaining: 9.49s
312:	total: 1.76s	remaining: 9.48s
313:	total: 1.76s	remaining: 9.47s
314:	total: 1.77s	remaining: 9.47s
315:	total: 1.77s	remaining: 9.46s
316:	total: 1.78s	remaining: 9.45s
317:	total: 1.78s	remaining: 9.43s
318:	total: 1.79s	remaining: 9.43s
319:	total: 1.79s	remaining: 9.42s
320:	total: 1.8s	remaining: 9.42s
321:	total: 1.8s	remaining: 9.41s
322:	total: 1.81s	remaining: 9.4s
323:	total: 1.81s	remaining: 9.39s
324:	total: 1.82s	remaining: 9.38s
325:	total: 1.82s	remaining: 9.37s
326:	total: 1.83s	remaining: 9.39s
327:	total: 1.84s	remaining: 9.4s
328:	total: 1.85s	remaining: 9.4s
329:	total: 1.85s	remaining: 9.39s
330:	total: 1.86s	remaining: 9.38s
331:	total: 1.87s	remaining: 9.38s
332:	total: 1.87s	remaining: 9.37s
333:	total: 1.88s	remaining: 9.36s
334:	total: 1.88s	remaining: 9.35s
335:	total: 1.88s	remaining: 9.33s
336:	total: 1.89s	remaining: 9.32s
337:	total: 1.9s	remaining: 9.33s
338:	total: 1.9s	remaining: 9.31s
339:	total: 1.91s	remaining: 9.3s
340:	total: 1.91s	remaining: 9.29s
341:	total: 1.91s	remaining: 9.28s
342:	total: 1.92s	remaining: 9.27s
343:	total: 1.92s	remaining: 9.26s
344:	total: 1.93s	remaining: 9.26s
345:	total: 1.93s	remaining: 9.25s
346:	total: 1.94s	remaining: 9.24s
347:	total: 1.94s	remaining: 9.23s
348:	total: 1.95s	remaining: 9.22s
349:	total: 1.95s	remaining: 9.21s
350:	total: 1.96s	remaining: 9.22s
351:	total: 1.97s	remaining: 9.21s
352:	total: 1.97s	remaining: 9.21s
353:	total: 1.98s	remaining: 9.21s
354:	total: 1.98s	remaining: 9.2s
355:	total: 1.99s	remaining: 9.19s
356:	total: 2s	remaining: 9.19s
357:	total: 2.01s	remaining: 9.2s
358:	total: 2.01s	remaining: 9.2s
359:	total: 2.02s	remaining: 9.2s
360:	total: 2.02s	remaining: 9.2s
361:	total: 2.03s	remaining: 9.19s
362:	total: 2.04s	remaining: 9.18s
363:	total: 2.04s	remaining: 9.18s
364:	total: 2.05s	remaining: 9.17s
365:	total: 2.05s	remaining: 9.16s
366:	total: 2.06s	remaining: 9.17s
367:	total: 2.07s	remaining: 9.17s
368:	total: 2.07s	remaining: 9.15s
369:	total: 2.08s	remaining: 9.15s
370:	total: 2.08s	remaining: 9.13s
371:	total: 2.08s	remaining: 9.13s
372:	total: 2.09s	remaining: 9.12s
373:	total: 2.09s	remaining: 9.11s
374:	total: 2.1s	remaining: 9.1s
375:	total: 2.1s	remaining: 9.09s
376:	total: 2.11s	remaining: 9.08s
377:	total: 2.11s	remaining: 9.07s
378:	total: 2.12s	remaining: 9.06s
379:	total: 2.12s	remaining: 9.05s
380:	total: 2.13s	remaining: 9.05s
381:	total: 2.14s	remaining: 9.05s
382:	total: 2.14s	remaining: 9.05s
383:	total: 2.15s	remaining: 9.04s
384:	total: 2.15s	remaining: 9.03s
385:	total: 2.16s	remaining: 9.03s
386:	total: 2.17s	remaining: 9.04s
387:	total: 2.17s	remaining: 9.03s
388:	total: 2.18s	remaining: 9.03s
389:	total: 2.19s	remaining: 9.03s
390:	total: 2.19s	remaining: 9.03s
391:	total: 2.2s	remaining: 9.03s
392:	total: 2.21s	remaining: 9.03s
393:	total: 2.21s	remaining: 9.02s
394:	total: 2.22s	remaining: 9.02s
395:	total: 2.23s	remaining: 9.02s
396:	total: 2.23s	remaining: 9.01s
397:	total: 2.24s	remaining: 9.01s
398:	total: 2.24s	remaining: 8.99s
399:	total: 2.25s	remaining: 8.98s
400:	total: 2.25s	remaining: 8.98s
401:	total: 2.26s	remaining: 8.97s
402:	total: 2.26s	remaining: 8.96s
403:	total: 2.27s	remaining: 8.95s
404:	total: 2.27s	remaining: 8.95s
405:	total: 2.27s	remaining: 8.93s
406:	total: 2.29s	remaining: 8.95s
407:	total: 2.29s	remaining: 8.96s
408:	total: 2.3s	remaining: 8.95s
409:	total: 2.3s	remaining: 8.94s
410:	total: 2.31s	remaining: 8.93s
411:	total: 2.31s	remaining: 8.92s
412:	total: 2.32s	remaining: 8.92s
413:	total: 2.33s	remaining: 8.92s
414:	total: 2.33s	remaining: 8.91s
415:	total: 2.34s	remaining: 8.9s
416:	total: 2.34s	remaining: 8.88s
417:	total: 2.35s	remaining: 8.88s
418:	total: 2.35s	remaining: 8.89s
419:	total: 2.36s	remaining: 8.87s
420:	total: 2.36s	remaining: 8.86s
421:	total: 2.37s	remaining: 8.86s
422:	total: 2.37s	remaining: 8.85s
423:	total: 2.38s	remaining: 8.84s
424:	total: 2.38s	remaining: 8.84s
425:	total: 2.39s	remaining: 8.83s
426:	total: 2.39s	remaining: 8.82s
427:	total: 2.4s	remaining: 8.81s
428:	total: 2.41s	remaining: 8.81s
429:	total: 2.41s	remaining: 8.81s
430:	total: 2.42s	remaining: 8.8s
431:	total: 2.42s	remaining: 8.8s
432:	total: 2.43s	remaining: 8.79s
433:	total: 2.43s	remaining: 8.78s
434:	total: 2.44s	remaining: 8.77s
435:	total: 2.44s	remaining: 8.76s
436:	total: 2.45s	remaining: 8.75s
437:	total: 2.45s	remaining: 8.75s
438:	total: 2.46s	remaining: 8.74s
439:	total: 2.46s	remaining: 8.73s
440:	total: 2.46s	remaining: 8.72s
441:	total: 2.47s	remaining: 8.71s
442:	total: 2.47s	remaining: 8.7s
443:	total: 2.48s	remaining: 8.7s
444:	total: 2.49s	remaining: 8.71s
445:	total: 2.5s	remaining: 8.7s
446:	total: 2.5s	remaining: 8.69s
447:	total: 2.5s	remaining: 8.68s
448:	total: 2.51s	remaining: 8.68s
449:	total: 2.52s	remaining: 8.68s
450:	total: 2.52s	remaining: 8.67s
451:	total: 2.53s	remaining: 8.66s
452:	total: 2.53s	remaining: 8.65s
453:	total: 2.54s	remaining: 8.64s
454:	total: 2.54s	remaining: 8.64s
455:	total: 2.55s	remaining: 8.63s
456:	total: 2.55s	remaining: 8.62s
457:	total: 2.56s	remaining: 8.61s
458:	total: 2.56s	remaining: 8.61s
459:	total: 2.57s	remaining: 8.6s
460:	total: 2.57s	remaining: 8.59s
461:	total: 2.58s	remaining: 8.58s
462:	total: 2.58s	remaining: 8.57s
463:	total: 2.59s	remaining: 8.56s
464:	total: 2.59s	remaining: 8.55s
465:	total: 2.6s	remaining: 8.54s
466:	total: 2.6s	remaining: 8.54s
467:	total: 2.61s	remaining: 8.55s
468:	total: 2.62s	remaining: 8.54s
469:	total: 2.62s	remaining: 8.53s
470:	total: 2.63s	remaining: 8.53s
471:	total: 2.63s	remaining: 8.52s
472:	total: 2.63s	remaining: 8.51s
473:	total: 2.64s	remaining: 8.5s
474:	total: 2.65s	remaining: 8.5s
475:	total: 2.65s	remaining: 8.49s
476:	total: 2.66s	remaining: 8.48s
477:	total: 2.66s	remaining: 8.48s
478:	total: 2.67s	remaining: 8.47s
479:	total: 2.67s	remaining: 8.47s
480:	total: 2.68s	remaining: 8.46s
481:	total: 2.68s	remaining: 8.45s
482:	total: 2.69s	remaining: 8.44s
483:	total: 2.69s	remaining: 8.44s
484:	total: 2.7s	remaining: 8.43s
485:	total: 2.71s	remaining: 8.43s
486:	total: 2.71s	remaining: 8.43s
487:	total: 2.72s	remaining: 8.42s
488:	total: 2.72s	remaining: 8.41s
489:	total: 2.73s	remaining: 8.4s
490:	total: 2.73s	remaining: 8.4s
491:	total: 2.74s	remaining: 8.39s
492:	total: 2.74s	remaining: 8.39s
493:	total: 2.75s	remaining: 8.38s
494:	total: 2.75s	remaining: 8.37s
495:	total: 2.76s	remaining: 8.36s
496:	total: 2.76s	remaining: 8.35s
497:	total: 2.77s	remaining: 8.36s
498:	total: 2.78s	remaining: 8.35s
499:	total: 2.78s	remaining: 8.35s
500:	total: 2.79s	remaining: 8.34s
501:	total: 2.79s	remaining: 8.33s
502:	total: 2.79s	remaining: 8.32s
503:	total: 2.8s	remaining: 8.32s
504:	total: 2.81s	remaining: 8.33s
505:	total: 2.82s	remaining: 8.33s
506:	total: 2.83s	remaining: 8.34s
507:	total: 2.84s	remaining: 8.34s
508:	total: 2.84s	remaining: 8.33s
509:	total: 2.85s	remaining: 8.32s
510:	total: 2.85s	remaining: 8.32s
511:	total: 2.86s	remaining: 8.31s
512:	total: 2.86s	remaining: 8.3s
513:	total: 2.87s	remaining: 8.29s
514:	total: 2.87s	remaining: 8.28s
515:	total: 2.88s	remaining: 8.28s
516:	total: 2.88s	remaining: 8.27s
517:	total: 2.88s	remaining: 8.26s
518:	total: 2.89s	remaining: 8.25s
519:	total: 2.9s	remaining: 8.24s
520:	total: 2.9s	remaining: 8.23s
521:	total: 2.9s	remaining: 8.23s
522:	total: 2.91s	remaining: 8.22s
523:	total: 2.91s	remaining: 8.21s
524:	total: 2.92s	remaining: 8.2s
525:	total: 2.92s	remaining: 8.19s
526:	total: 2.93s	remaining: 8.18s
527:	total: 2.94s	remaining: 8.19s
528:	total: 2.94s	remaining: 8.18s
529:	total: 2.94s	remaining: 8.17s
530:	total: 2.95s	remaining: 8.16s
531:	total: 2.96s	remaining: 8.15s
532:	total: 2.96s	remaining: 8.14s
533:	total: 2.96s	remaining: 8.14s
534:	total: 2.97s	remaining: 8.13s
535:	total: 2.98s	remaining: 8.13s
536:	total: 2.98s	remaining: 8.12s
537:	total: 2.99s	remaining: 8.12s
538:	total: 2.99s	remaining: 8.11s
539:	total: 3s	remaining: 8.11s
540:	total: 3s	remaining: 8.1s
541:	total: 3.01s	remaining: 8.1s
542:	total: 3.01s	remaining: 8.09s
543:	total: 3.02s	remaining: 8.08s
544:	total: 3.02s	remaining: 8.07s
545:	total: 3.03s	remaining: 8.06s
546:	total: 3.03s	remaining: 8.06s
547:	total: 3.04s	remaining: 8.05s
548:	total: 3.04s	remaining: 8.04s
549:	total: 3.05s	remaining: 8.03s
550:	total: 3.05s	remaining: 8.03s
551:	total: 3.06s	remaining: 8.02s
552:	total: 3.06s	remaining: 8.01s
553:	total: 3.07s	remaining: 8s
554:	total: 3.07s	remaining: 8s
555:	total: 3.08s	remaining: 7.99s
556:	total: 3.08s	remaining: 7.98s
557:	total: 3.08s	remaining: 7.97s
558:	total: 3.09s	remaining: 7.96s
559:	total: 3.1s	remaining: 7.96s
560:	total: 3.1s	remaining: 7.96s
561:	total: 3.11s	remaining: 7.95s
562:	total: 3.11s	remaining: 7.94s
563:	total: 3.12s	remaining: 7.93s
564:	total: 3.12s	remaining: 7.92s
565:	total: 3.13s	remaining: 7.92s
566:	total: 3.13s	remaining: 7.92s
567:	total: 3.14s	remaining: 7.91s
568:	total: 3.14s	remaining: 7.91s
569:	total: 3.15s	remaining: 7.9s
570:	total: 3.15s	remaining: 7.89s
571:	total: 3.16s	remaining: 7.89s
572:	total: 3.16s	remaining: 7.88s
573:	total: 3.17s	remaining: 7.87s
574:	total: 3.18s	remaining: 7.88s
575:	total: 3.18s	remaining: 7.87s
576:	total: 3.19s	remaining: 7.86s
577:	total: 3.2s	remaining: 7.87s

# Submission

In [295]:
df_test_ = pd.read_csv(f"{root_path}/test.csv")
df_test = prep_df(df_test_)

In [296]:
def age_bucket(age):
    if age < 30:
        return "Young"
    if age < 60:
        return "Adult"
    return "Senior"


subtask1 = df_test_["age"].apply(age_bucket)

In [297]:
def dti_bucket(dti):
    if dti < 20:
        return "LowRisk"
    if dti < 40:
        return "MediumRisk"
    return "HighRisk"


subtask2 = df_test_["debt_to_income_ratio"].apply(dti_bucket)

In [298]:
subtask3 = (
    df_test_["current_debt"] +
    df_test_["derogatory_marks"] +
    df_test_["delinquencies_last_2yrs"]
).astype(int)

In [302]:
subtask4 = model.predict_proba(df_test)[:, 1]

In [303]:
subtasks = [
    (1, subtask1),
    (2, subtask2),
    (3, subtask3),
    (4, subtask4),
]


def build_subtask(sid, answer):
    return pd.DataFrame(
        {"subtaskID": sid, "datapointID": df_test_["customer_id"], "answer": answer}
    )


submission = pd.concat([build_subtask(sid, ans) for sid, ans in subtasks])
submission.head()

   subtaskID datapointID answer
0          1  CUST146767  Adult
1          1  CUST136829  Adult
2          1  CUST119409  Young
3          1  CUST112393  Young
4          1  CUST143342  Adult

In [304]:
submission.to_csv(f"{root_path}/submission.csv", index=False)