In [ ]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk import WordNetLemmatizer
import string

from transformers import AutoTokenizer, AutoModelForMaskedLM
import torch
from torch.utils.data import Dataset, DataLoader

In [ ]:
root_path = "/home/stefan/ioai-prep/kits/essay-gap"
device = "cuda" if torch.cuda.is_available() else "cpu"

seed = 42
torch.random.manual_seed(seed)

# Dataset

In [3]:
stop_words = set(stopwords.words("english"))
to_remove = stop_words | set(string.punctuation)

lemmatizer = WordNetLemmatizer()

def clean_text(text: str):
    return text
    text = text.lower()
    tok = nltk.word_tokenize(text)
    tok = [lemmatizer.lemmatize(t) for t in tok if t not in to_remove]
    return ' '.join(tok)

clean_text("Ana has apples.")

'Ana has apples.'

In [4]:
train_df = pd.read_csv(f"{root_path}/train.csv")

for col in train_df.select_dtypes(include='object'):
    train_df[col] = train_df[col].apply(clean_text)

train_df.head()

,sampleID,before,after,opt_0,opt_1,opt_2,opt_3,label
0,0,"In China, nationalist and communist forces res...","In the Middle East, the Arab rejection of the ...",Dogs are domesticated members of the family Ca...,The AD 493 Book of Song quotes the frontier ge...,Communist forces prevailed and established the...,Dead position: If neither player is able to ch...,2
1,1,In The Structure and Distribution of Coral Ree...,"As the subsidence continues, the fringing reef...",A fringing reef forms around an extinct volcan...,Coral larvae cannot settle on sand; they can o...,Popular Motown recordings of the late 1960s an...,"This may be remembered by the phrases ""white o...",0
2,2,Coral reef restoration has grown in prominence...,"With the deterioration of global reefs, fish n...","Following Hindenburg's death in 1934, Hitler p...","Coral stressors can include pollution, warming...","A violin is tuned in fifths, in the notes G3, ...",Roosevelt reinforced the Philippines (an Ameri...,1
3,3,"World War II transformed the political, econom...",Many countries whose industries had been damag...,Walter Chandoha made his career photographing ...,"From Python 2.5 on, it is possible to pass dat...",Jon Krakauer's Into Thin Air (1997) expressed ...,"In the wake of Europe's devastation, the influ...",3
4,4,Another important strategic question in the mi...,Not every reduction of material is good for th...,"A male cat is called a tom, tommy or tomcat (o...",Commonly cited reasons for not using bitcoin i...,Minor material advantages can generally be tra...,"However, house cats' behavior is also influenc...",2

In [ ]:
class EssayDataset:
    def __init__():
        pass

# Model

# Training

# Submission

In [5]:
test_df = pd.read_csv(f"{root_path}/test.csv")

for col in train_df.select_dtypes(include="object"):
    test_df[col] = test_df[col].apply(clean_text)

In [6]:
submission = pd.DataFrame({"sampleID": test_df["sampleID"], "answer": 0})
submission.head()

   sampleID  answer
0       100       0
1       101       0
2       102       0
3       103       0
4       104       0

In [7]:
submission.to_csv("submission.csv", index=False)